# Content Structure Contract for Digital Twin Module

openapi: 3.0.0
info:
  title: Digital Twin Educational Content Structure
  description: Specification for the structure and organization of digital twin educational content
  version: 1.0.0

paths: {}

components:
  schemas:
    Chapter:
      type: object
      required:
        - id
        - title
        - learningObjectives
        - content
        - keyTakeaways
      properties:
        id:
          type: string
          description: Unique identifier for the chapter
          example: "introduction" or "physics-simulation"
        title:
          type: string
          description: Display title of the chapter
          example: "Introduction to Digital Twins"
        learningObjectives:
          type: array
          items:
            type: string
          description: List of learning objectives for the chapter
          example: ["Understand what digital twins are", "Explain their relevance to Physical AI"]
        content:
          type: string
          description: Main content of the chapter in Markdown format
        keyTakeaways:
          type: array
          items:
            type: string
          description: Key points to remember from the chapter
        furtherReading:
          type: array
          items:
            type: string
          description: Additional resources for deeper understanding
          example: ["Official Gazebo documentation", "Unity robotics toolkit"]

    DigitalTwinModule:
      type: object
      required:
        - id
        - title
        - chapters
        - categoryConfig
      properties:
        id:
          type: string
          description: Unique identifier for the module
          example: "digital-twin"
        title:
          type: string
          description: Display title of the module
          example: "The Digital Twin (Gazebo & Unity)"
        chapters:
          type: array
          items:
            $ref: '#/components/schemas/Chapter'
          description: List of chapters in the module
          minItems: 4
          maxItems: 4
        categoryConfig:
          type: object
          description: Configuration for Docusaurus category display
          properties:
            label:
              type: string
              description: Display label for the category
              example: "Digital Twin Concepts"
            position:
              type: integer
              description: Position in navigation
              example: 3
            link:
              type: object
              properties:
                type:
                  type: string
                  description: Type of link
                  enum: [doc]
                id:
                  type: string
                  description: ID of the default doc to show
                  example: "introduction"

    ContentRequirements:
      type: object
      properties:
        format:
          type: string
          description: Required format for content
          enum: [markdown]
          example: "markdown"
        technicalFocus:
          type: string
          description: Technical focus of the content
          enum: [conceptual, simulation-focused]
          example: "simulation-focused"
        hardwareSpecific:
          type: boolean
          description: Whether content includes hardware-specific instructions
          example: false
        targetAudience:
          type: string
          description: Intended audience for the content
          example: "Robotics researchers and developers"